# version: '3.8'

services:
  api:
    # THE MATHEMATICAL TRUTH: Points directly to your Docker Hub
    image: swbanga1/fastapi:latest 
    build:
      context: .
    # (Keep your existing ports, environment variables, and depends_on here)
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    restart: always
    # Absolute lockdown: Zero host ports exposed.